language: go

go:
  - 1.8
  - 1.9

matrix:
  fast_finish: true

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/stretchr/testify/require

script:
  - go test -v -race -cover ./...